export const ADD_MOVIES = 'ADD_MOVIES'
export const SET_SEARCH_BY = 'SET_SEARCH_BY'
export const SET_SORT_BY = 'SET_SORT_BY'
export const SET_QUERY = 'SET_QUERY'
export const RISE_LIMIT = 'RISE_LIMIT'
